site_name: decopatch
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/python-decopatch
docs_dir: .
site_dir: ../site
nav:
    - Home: index.md
    - Motivation: motivation.md
    - Disambiguation principes: disambiguation.md
#    - Usage details: usage_details.md
    - PEP proposal: pep_proposal.md
    - Changelog: changelog.md

theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true